name: 'BTC'
version: '1.0.0'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

models:
  BTC:
    marts:
      +materialized: table
    post-hook:
      - "{{ create_latest_version_view() }}"

